-- 창업진흥원 K-Startup 조회서비스(15125364) + 수집 로그
-- Supabase SQL Editor에서 실행하거나 apply 스크립트로 적용하십시오.
-- 페이지 단위: 100건 (announcements / business / contents / statistics)

create table if not exists public.kstartup_announcements (
  id bigint generated by default as identity primary key,
  pbanc_sn text not null,
  biz_pbanc_nm text not null default '',
  intg_pbanc_biz_nm text not null default '',
  intg_pbanc_yn text not null default '',
  rcrt_prgs_yn text not null default '',
  supt_biz_clsfc text not null default '',
  supt_regin text not null default '',
  aply_trgt text not null default '',
  aply_trgt_ctnt text not null default '',
  biz_enyy text not null default '',
  biz_trgt_age text not null default '',
  prfn_matr text not null default '',
  pbanc_ctnt text not null default '',
  pbanc_rcpt_bgng_dt text not null default '',
  pbanc_rcpt_end_dt text not null default '',
  pbanc_ntrp_nm text not null default '',
  sprv_inst text not null default '',
  biz_prch_dprt_nm text not null default '',
  prch_cnpl_no text not null default '',
  biz_gdnc_url text not null default '',
  biz_aply_url text not null default '',
  detl_pg_url text not null default '',
  aply_excl_trgt_ctnt text not null default '',
  page_no integer not null default 1,
  raw jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (pbanc_sn)
);

create index if not exists kstartup_announcements_fetched_at_idx
  on public.kstartup_announcements (fetched_at desc);
create index if not exists kstartup_announcements_region_idx
  on public.kstartup_announcements (supt_regin, rcrt_prgs_yn);
create index if not exists kstartup_announcements_clsfc_idx
  on public.kstartup_announcements (supt_biz_clsfc, sprv_inst);
create index if not exists kstartup_announcements_period_idx
  on public.kstartup_announcements (pbanc_rcpt_bgng_dt, pbanc_rcpt_end_dt);

alter table public.kstartup_announcements enable row level security;

drop policy if exists "public can read kstartup announcements"
  on public.kstartup_announcements;
create policy "public can read kstartup announcements"
  on public.kstartup_announcements
  for select to anon, authenticated
  using (true);

drop policy if exists "anon can upsert kstartup announcements"
  on public.kstartup_announcements;
create policy "anon can upsert kstartup announcements"
  on public.kstartup_announcements
  for insert to anon, authenticated
  with check (true);

drop policy if exists "anon can update kstartup announcements"
  on public.kstartup_announcements;
create policy "anon can update kstartup announcements"
  on public.kstartup_announcements
  for update to anon, authenticated
  using (true)
  with check (true);

create table if not exists public.kstartup_business (
  id bigint generated by default as identity primary key,
  biz_key text not null,
  biz_yr text not null default '',
  biz_category_cd text not null default '',
  supt_biz_titl_nm text not null default '',
  biz_supt_trgt_info text not null default '',
  biz_supt_bdgt_info text not null default '',
  biz_supt_ctnt text not null default '',
  supt_biz_chrct text not null default '',
  supt_biz_intrd_info text not null default '',
  detl_pg_url text not null default '',
  page_no integer not null default 1,
  raw jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (biz_key)
);

create index if not exists kstartup_business_fetched_at_idx
  on public.kstartup_business (fetched_at desc);
create index if not exists kstartup_business_year_idx
  on public.kstartup_business (biz_yr, biz_category_cd);

alter table public.kstartup_business enable row level security;

drop policy if exists "public can read kstartup business"
  on public.kstartup_business;
create policy "public can read kstartup business"
  on public.kstartup_business
  for select to anon, authenticated
  using (true);

drop policy if exists "anon can upsert kstartup business"
  on public.kstartup_business;
create policy "anon can upsert kstartup business"
  on public.kstartup_business
  for insert to anon, authenticated
  with check (true);

drop policy if exists "anon can update kstartup business"
  on public.kstartup_business;
create policy "anon can update kstartup business"
  on public.kstartup_business
  for update to anon, authenticated
  using (true)
  with check (true);

create table if not exists public.kstartup_contents (
  id bigint generated by default as identity primary key,
  content_key text not null,
  titl_nm text not null default '',
  clss_cd text not null default '',
  file_nm text not null default '',
  view_cnt integer not null default 0,
  fstm_reg_dt text not null default '',
  detl_pg_url text not null default '',
  page_no integer not null default 1,
  raw jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (content_key)
);

create index if not exists kstartup_contents_fetched_at_idx
  on public.kstartup_contents (fetched_at desc);
create index if not exists kstartup_contents_clss_idx
  on public.kstartup_contents (clss_cd, view_cnt desc);

alter table public.kstartup_contents enable row level security;

drop policy if exists "public can read kstartup contents"
  on public.kstartup_contents;
create policy "public can read kstartup contents"
  on public.kstartup_contents
  for select to anon, authenticated
  using (true);

drop policy if exists "anon can upsert kstartup contents"
  on public.kstartup_contents;
create policy "anon can upsert kstartup contents"
  on public.kstartup_contents
  for insert to anon, authenticated
  with check (true);

drop policy if exists "anon can update kstartup contents"
  on public.kstartup_contents;
create policy "anon can update kstartup contents"
  on public.kstartup_contents
  for update to anon, authenticated
  using (true)
  with check (true);

create table if not exists public.kstartup_statistics (
  id bigint generated by default as identity primary key,
  stats_key text not null,
  titl_nm text not null default '',
  file_nm text not null default '',
  ctnt text not null default '',
  fstm_reg_dt text not null default '',
  last_mdfcn_dt text not null default '',
  detl_pg_url text not null default '',
  page_no integer not null default 1,
  raw jsonb not null default '{}'::jsonb,
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (stats_key)
);

create index if not exists kstartup_statistics_fetched_at_idx
  on public.kstartup_statistics (fetched_at desc);

alter table public.kstartup_statistics enable row level security;

drop policy if exists "public can read kstartup statistics"
  on public.kstartup_statistics;
create policy "public can read kstartup statistics"
  on public.kstartup_statistics
  for select to anon, authenticated
  using (true);

drop policy if exists "anon can upsert kstartup statistics"
  on public.kstartup_statistics;
create policy "anon can upsert kstartup statistics"
  on public.kstartup_statistics
  for insert to anon, authenticated
  with check (true);

drop policy if exists "anon can update kstartup statistics"
  on public.kstartup_statistics;
create policy "anon can update kstartup statistics"
  on public.kstartup_statistics
  for update to anon, authenticated
  using (true)
  with check (true);

create table if not exists public.kstartup_fetch_logs (
  id bigint generated by default as identity primary key,
  resource text not null default 'announcements'
    check (resource in ('announcements', 'business', 'contents', 'statistics')),
  page_no integer not null default 1,
  page_size integer not null default 100,
  row_count integer not null default 0 check (row_count >= 0),
  total_count integer not null default 0,
  params jsonb not null default '{}'::jsonb,
  status text not null default 'ok' check (status in ('ok', 'error')),
  error_message text not null default '',
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists kstartup_fetch_logs_fetched_at_idx
  on public.kstartup_fetch_logs (fetched_at desc);
create index if not exists kstartup_fetch_logs_resource_idx
  on public.kstartup_fetch_logs (resource, fetched_at desc);

alter table public.kstartup_fetch_logs enable row level security;

drop policy if exists "public can read kstartup fetch logs"
  on public.kstartup_fetch_logs;
create policy "public can read kstartup fetch logs"
  on public.kstartup_fetch_logs
  for select to anon, authenticated
  using (true);

drop policy if exists "anon can insert kstartup fetch logs"
  on public.kstartup_fetch_logs;
create policy "anon can insert kstartup fetch logs"
  on public.kstartup_fetch_logs
  for insert to anon, authenticated
  with check (true);
